services:
  backend:
    build: ./Backend
    container_name: backend-container
    ports:
      - "5000:5000"

  frontend:
    build: ./Frontend
    container_name: frontend-container
    ports:
      - "80:80"
    depends_on:
      - backend
