name: Deploy App

on:
  workflow_dispatch:

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3

      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22

        script: |

          cd /home/ec2-user

          # clone repo first time
          if [ ! -d "Test-Project" ]; then
            git clone https://github.com/Protyusa/Test-Project-1.git
          fi

          cd Test-Project-1

          git pull origin main

          # stop old containers
          sudo docker stop frontend-container || true
          sudo docker stop backend-container || true

          sudo docker rm frontend-container || true
          sudo docker rm backend-container || true

          # build backend
          sudo docker build -t backend-app ./backend

          # build frontend
          sudo docker build -t frontend-app ./frontend

          # run backend
          sudo docker run -d -p 5000:5000 --name backend-container backend-app

          # run frontend
          sudo docker run -d -p 80:3000 --name frontend-container frontend-app
